name: Trigger auto deployment for novellus-loan-calculator

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Codebase ]
    paths:
    - '**'
    - '.github/workflows/novellus-loan-calculator-AutoDeployTrigger-1abbbe89-b30e-40b9-af8b-f4fc79d901f4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NOVELLUSLOANCALCULATOR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NOVELLUSLOANCALCULATOR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NOVELLUSLOANCALCULATOR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: applications.azurecr.io
          registryUsername: ${{ secrets.NOVELLUSLOANCALCULATOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NOVELLUSLOANCALCULATOR_REGISTRY_PASSWORD }}
          containerAppName: novellus-loan-calculator
          resourceGroup: rg-crm-staging
          imageToBuild: applications.azurecr.io/novellus-loan-calculator:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


